manifest = "8adb814707a8aa183941607049ec5f3524186c86f95414fbfefb754899838605"

[[dependency]]
package = "github.com/buckaroo-pm/google-googletest"
target = "//:googletest"

[lock."github.com/buckaroo-pm/google-googletest"]
versions = [ "branch=master" ]
revision = "cb8d2c1a2fcd344953e6c129a1a699a2c230551d"
